### ISSUE TITLE
The Egg disappeared

### ISSUE THREAD

**Issue by grugnoymeme** [MrModd/Matagotchi#1]
I launched the fap. The Egg bounced for a while (something like 3-4 minutes) and then disappeared... and i couldn't do NOTHING else more...

**Comment by MrModd** [comment]
The app is in the very early stages.
The egg is the only image I drew up to now.
The reason why you can't do anything else is because the state is persisted in the SDCard under /ext/apps_data/matagotchi/. You can remove the file to restore the initial state of the game.

**Comment by MrModd** [comment]
Just to clarify I'm focusing my effort on the backend for now. I need to have a stable structure behind before passing to user inputs and interface.

**Comment by grugnoymeme** [comment]
i understand!! so wait for the complete v1.o :)
