### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by DefinetlyNotAI** [MrModd/Matagotchi#5]
Maybe add more features?  Like different pets, maybe minigames that incorporate the nfc/rfid functions?

**Comment by MrModd** [comment]
Hi,
I will. I'm busy with work, the time I manage to dedicate to this project is not much.
What do you suggest to do with nfc?

**Comment by DefinetlyNotAI** [comment]
Hmm, maybe make it _eat_ the scanned nfc? gain more xp that way?

**Comment by MrModd** [comment]
That's a good idea. Something like the Nintendo Amiibo.
I'll figure out something. Thanks!

**Comment by DefinetlyNotAI** [comment]
ISTG I thought of saying amiibo :0

But np, i would help, but i hate C

**Comment by DefinetlyNotAI** [comment]
also maybe, make some nfc/amiibo do a cool animation/effect, like reverse aging (i got trauma from my tomogotchi's death
